defaults: &defaults
  adapter: postgresql
  username: <%= ENV['DATABASE_USER'] || ENV['POSTGRES_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] || ENV['POSTGRES_PASSWORD'] %>
  collation: 'es_ES.UTF-8'
  ctype: 'es_ES.UTF-8'
  template: 'template0'
  encoding: 'UTF8'

development:
  <<: *defaults
  database: <%= ENV.fetch('DATABASE_NAME', 'timeoverflow_development') %>

test:
  <<: *defaults
  database: 'timeoverflow_test'

staging:
  <<: *defaults
  database: <%= ENV.fetch('DATABASE_NAME', 'timeoverflow_staging') %>

production:
  <<: *defaults
  database: <%= ENV.fetch('DATABASE_NAME', 'timeoverflow_production') %>
